---
    kind: pipeline
    type: docker
    name: default
    
    steps:
    - name: build
      image: golang:1.13.5
      commands:
      - go build  --buildmode=plugin plugin.go

    - name: publish
      image: plugins/docker
      settings:
        repo: ghcr.io/monkiato/game-server-plugin-realtime-multiplayer
        registry: ghcr.io
        tags: ${DRONE_TAG}
        username:
          from_secret: docker_username
        password:
          from_secret: docker_password
      when:
        event:
          - tag

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head
    - refs/tags/*
