---
    kind: pipeline
    type: docker
    name: default
    
    steps:
    - name: build
      image: golang:1.13.5
      commands:
      - go build --buildmode=plugin -o dist/realtime_multiplayer_plugin.so plugin.go

    - name: publish
      image: plugins/github-release
      settings:
        api_key:
          from_secret: github_api_key
        files: dist/*
      when:
        event:
          - tag

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head
    - refs/tags/*
