// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package multiplayer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreateMatchInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsCreateMatchInfo(buf []byte, offset flatbuffers.UOffsetT) *CreateMatchInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreateMatchInfo{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCreateMatchInfo(buf []byte, offset flatbuffers.UOffsetT) *CreateMatchInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CreateMatchInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *CreateMatchInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreateMatchInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func CreateMatchInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func CreateMatchInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
