// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package multiplayer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LeaveMatchResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsLeaveMatchResponse(buf []byte, offset flatbuffers.UOffsetT) *LeaveMatchResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LeaveMatchResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLeaveMatchResponse(buf []byte, offset flatbuffers.UOffsetT) *LeaveMatchResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LeaveMatchResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LeaveMatchResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LeaveMatchResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LeaveMatchResponse) Status() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *LeaveMatchResponse) MutateStatus(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func LeaveMatchResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LeaveMatchResponseAddStatus(builder *flatbuffers.Builder, status bool) {
	builder.PrependBoolSlot(0, status, false)
}
func LeaveMatchResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
