// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package multiplayer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RequestPlayerInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsRequestPlayerInfo(buf []byte, offset flatbuffers.UOffsetT) *RequestPlayerInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RequestPlayerInfo{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRequestPlayerInfo(buf []byte, offset flatbuffers.UOffsetT) *RequestPlayerInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RequestPlayerInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RequestPlayerInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RequestPlayerInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RequestPlayerInfo) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RequestPlayerInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RequestPlayerInfoAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func RequestPlayerInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
